<?php

use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = \Faker\Factory::create();

        $products = [
            [
                'code' => '',
                'category_id' => '1',
                'name' => 'Dinuguan',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'dinuguan',
                'is_featured' => '1',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '3',
                'name' => 'Chopsuey',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'is_featured' => '0',
                'uom' => 'PC',
                'slug' => 'chopsuey',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '1',
                'name' => 'Laing con Lechon',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PRIVATE',
                'uom' => 'PC',
                'slug' => 'laing-con-lechon',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '2',
                'name' => 'LQM Chopsuey',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'lqm-chopsuey',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '1',
                'name' => 'Fresh Lumpia',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'fresh-lumpia',
                'is_featured' => '1',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '1',
                'name' => 'Kare-kare Classic',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'kare-kare-classic',
                'is_featured' => '1',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '1',
                'name' => 'Lechon Paksiw',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'lechon-paksiw',
                'is_featured' => '1',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '1',
                'name' => 'Lechon Sinigang',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'lechon-sinigang',
                'is_featured' => '1',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '1',
                'name' => 'Lechon Sisig',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'lechon-sisig',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '1',
                'name' => 'Pancit canton con Lechon',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'pancit-canton-con-lechon',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '1',
                'name' => 'Pinakbet',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'pinakbet',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '1',
                'name' => 'Sinigang na Ulo ng Salmon',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'sinigang-na-ulo-ng-salmon',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '2',
                'name' => 'LQM Dinuguan',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'lqm-dinuguan',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '2',
                'name' => 'LQM Kare-kare',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'lqm-kare-kare',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '2',
                'name' => 'LQM Pinakbet',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'lqm-pinakbet',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '5',
                'name' => 'Kare-kare con Lechon',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'kare-kare-con-lechon',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '5',
                'name' => 'Sizzling Bopis',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'sizzling-bopis',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '6',
                'name' => 'Dinuguan with Puto',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'dinuguan-with-puto',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '6',
                'name' => 'Lumpiang Ubod Prito',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'lumpiang-ubod-prito',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '6',
                'name' => 'Pancit Mixed',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'pancit-mixed',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '8',
                'name' => 'Chicharon Bituka',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'chicharon-bituka',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '8',
                'name' => 'Garlic Chicharon Bulaklak',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'garlic-chicharon-bulaklak',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '8',
                'name' => 'Manggat Bagoong',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'manggat-bagoong',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '9',
                'name' => 'Buko Pandan',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'buko-pandan',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '9',
                'name' => 'Leche Flan Small',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'leche-flan-small',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '9',
                'name' => 'Mango Sago',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'mango-sago',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '10',
                'name' => 'Beef Papaitan',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'beef-papaitan',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '11',
                'name' => 'Bangus Ala Pobre',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'bangus-ala-pobre',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '11',
                'name' => 'Rellenong Alimango',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'rellenong-alimango',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '4',
                'name' => '1/2 kg Lechon',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => '12-kg-lechon',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => '',
                'category_id' => '4',
                'name' => '1/4 Kilo Lechon',
                'short_description' => '',
                'description' => '',
                'price' => '0.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '0',
                'for_sale_web' => '0',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => '14-kilo-lechon',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            //
            [
                'code' => 'L001',
                'category_id' => '0',
                'name' => 'Whole Lechon (Small)',
                'short_description' => '',
                'description' => '',
                'price' => '7800.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => 'De Leche',
                'no_of_pax' => '15-20 pax',
                'for_sale' => '1',
                'for_sale_web' => '1',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'whole-lechon-small',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '2500.0000',
            ],
            [
                'code' => 'L002',
                'category_id' => '0',
                'name' => 'Whole Lechon (Small)',
                'short_description' => '',
                'description' => '',
                'price' => '8800.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '8-9 Kg',
                'no_of_pax' => '20-25 pax',
                'for_sale' => '1',
                'for_sale_web' => '1',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'whole-lechon-small',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '2500.0000',
            ],
            [
                'code' => 'L003',
                'category_id' => '0',
                'name' => 'Whole Lechon (Small)',
                'short_description' => '',
                'description' => '',
                'price' => '9800.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '10-12 Kg',
                'no_of_pax' => '25-30 pax',
                'for_sale' => '1',
                'for_sale_web' => '1',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'whole-lechon-small',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '2500.0000',
            ],
            [
                'code' => 'L004',
                'category_id' => '0',
                'name' => 'Whole Lechon (Medium)',
                'short_description' => '',
                'description' => '',
                'price' => '10800.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '13-15 Kg',
                'no_of_pax' => '35-40 pax',
                'for_sale' => '1',
                'for_sale_web' => '1',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'whole-lechon-medium',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '3500.0000',
            ],
            [
                'code' => 'L005',
                'category_id' => '0',
                'name' => 'Whole Lechon (Medium)',
                'short_description' => '',
                'description' => '',
                'price' => '11800.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '16 Kg',
                'no_of_pax' => '45-50 pax',
                'for_sale' => '1',
                'for_sale_web' => '1',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'whole-lechon-medium',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '3500.0000',
            ],
            [
                'code' => 'L006',
                'category_id' => '0',
                'name' => 'Whole Lechon (Medium)',
                'short_description' => '',
                'description' => '',
                'price' => '12800.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '17-19 Kg',
                'no_of_pax' => '60-70 pax',
                'for_sale' => '1',
                'for_sale_web' => '1',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'whole-lechon-medium',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '3500.0000',
            ],
            [
                'code' => 'L007',
                'category_id' => '0',
                'name' => 'Whole Lechon (Large)',
                'short_description' => '',
                'description' => '',
                'price' => '13800.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '20-22 Kg',
                'no_of_pax' => '55-90 pax',
                'for_sale' => '1',
                'for_sale_web' => '1',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'whole-lechon-large',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '4500.0000',
            ],
            [
                'code' => 'L008',
                'category_id' => '0',
                'name' => 'Whole Lechon (Large)',
                'short_description' => '',
                'description' => '',
                'price' => '14800.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '23-25 Kg',
                'no_of_pax' => '95-100 pax',
                'for_sale' => '1',
                'for_sale_web' => '1',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'whole-lechon-large',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '4500.0000',
            ],
            [
                'code' => 'L009',
                'category_id' => '0',
                'name' => 'Whole Lechon (Large)',
                'short_description' => '',
                'description' => '',
                'price' => '15800.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '26-30 Kg',
                'no_of_pax' => '110-130 pax',
                'for_sale' => '1',
                'for_sale_web' => '1',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'whole-lechon-large',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '4500.0000',
            ],
            [
                'code' => 'L010',
                'category_id' => '0',
                'name' => 'Whole Lechon (X-Large)',
                'short_description' => '',
                'description' => '',
                'price' => '16800.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '32-35 Kg',
                'no_of_pax' => '140-160 pax',
                'for_sale' => '1',
                'for_sale_web' => '1',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'whole-lechon-x-large',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '5500.0000',
            ],
            [
                'code' => 'L010',
                'category_id' => '0',
                'name' => 'Lechon Baka',
                'short_description' => '',
                'description' => '',
                'price' => '52000.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '100-120 Kg',
                'no_of_pax' => '150-200 pax',
                'for_sale' => '1',
                'for_sale_web' => '1',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'lechon-baka',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => 'L010',
                'category_id' => '0',
                'name' => 'Lechon-In-A-Box',
                'short_description' => '',
                'description' => '<div class="del-options my-3"><p>Also available on:</p><img src="http://localhost:8000/storage/file-manager/file-manager/Others/fd1.png" /><img src="http://localhost:8000/storage/file-manager/file-manager/Others/fd2.png" /><img src="http://localhost:8000/storage/file-manager/file-manager/Others/fd3.png" /></div>',
                'price' => '2500.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '-',
                'no_of_pax' => '10-12 pax',
                'for_sale' => '1',
                'for_sale_web' => '1',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'lechon-in-a-box',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => 'L010',
                'category_id' => '0',
                'name' => 'Lechon In A Box 1',
                'short_description' => '',
                'description' => '<div class="del-options my-3"><p>Also available on:</p><img src="http://localhost:8000/storage/file-manager/file-manager/Others/fd1.png" /><img src="http://localhost:8000/storage/file-manager/file-manager/Others/fd2.png" /><img src="http://localhost:8000/storage/file-manager/file-manager/Others/fd3.png" /></div>',
                'price' => '2500.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '1',
                'for_sale_web' => '1',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'lechon-in-a-box-1',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],
            [
                'code' => 'L010',
                'category_id' => '0',
                'name' => 'Lechon In A Box 2',
                'short_description' => '',
                'description' => '<div class="del-options my-3"><p>Also available on:</p><img src="http://localhost:8000/storage/file-manager/file-manager/Others/fd1.png" /><img src="http://localhost:8000/storage/file-manager/file-manager/Others/fd2.png" /><img src="http://localhost:8000/storage/file-manager/file-manager/Others/fd3.png" /></div>',
                'price' => '2500.0000',
                'currency' => 'PHP',
                'size' => '',
                'weight' => '',
                'no_of_pax' => '',
                'for_sale' => '1',
                'for_sale_web' => '1',
                'status' => 'PUBLISHED',
                'uom' => 'PC',
                'slug' => 'lechon-in-a-box-2',
                'is_featured' => '0',
                'created_by' => 1,
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'paella_price' => '0.0000',
            ],

        ];

        DB::table('products')->insert($products);
    }
}
